[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d80730e510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d808252270>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d80730eb40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d80730fd40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d80730cb90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76d80730dbb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/cf464adb754345b07896ddc0939212fe